ktor {
    deployment {
        port = ${SPLIT_THE_BILL_DEV_PORT}
    }
    application {
        modules = [com.system.ApplicationKt.module]
    }
    development = true
    deployment {
       watch = [ classes ]
    }
}

resend {
    key = ${SPLIT_THE_BILL_RESEND_API_KEY}
}

jwt {
    secret = ${SPLIT_THE_BILL_JWT_SECRET}
    issuer = "split-the-bill-api"
    audience = "split-the-bill-app"
    realm = "Split The Bill API"
}