package com.system.theme

import androidx.compose.ui.graphics.Color
import androidx.compose.material3.lightColorScheme

val PrimaryLight = Color(0xFF000000)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFF36353E)
val OnPrimaryContainerLight = Color(0xFF4D4E65)
val InversePrimaryLight = Color(0xFFDEDDFA)
val SecondaryLight = Color(0xFF4E4E4E)
val OnSecondaryLight = Color(0xFFF1FFCD)
val SecondaryContainerLight = Color(0xFFE8F7C3)
val OnSecondaryContainerLight = Color(0xFF525F37)
val TertiaryLight = Color(0xFF526700)
val OnTertiaryLight = Color(0xFFF3FFC4)
val TertiaryContainerLight = Color(0xFFE2FC8B)
val OnTertiaryContainerLight = Color(0xFF4E6100)
val BackgroundLight = Color(0xFFFDF8FF)
val OnBackgroundLight = Color(0xFF332D55)
val SurfaceLight = Color(0xFFFDF8FF)
val OnSurfaceLight = Color(0xFF332D55)
val SurfaceVariantLight = Color(0xFFE5DEFF)
val OnSurfaceVariantLight = Color(0xFF605A85)
val SurfaceTintLight = Color(0xFF5C5D75)
val InverseSurfaceLight = Color(0xFF0E0B20)
val InverseOnSurfaceLight = Color(0xFF9F99B5)
val ErrorLight = Color(0xFFAC3149)
val OnErrorLight = Color(0xFFFFF7F7)
val ErrorContainerLight = Color(0xFFF76A80)
val OnErrorContainerLight = Color(0xFF68001F)
val OutlineLight = Color(0xFF7C75A3)
val OutlineVariantLight = Color(0xFFB4ACDD)
val ScrimLight = Color(0xFF000000)
val SurfaceBrightLight = Color(0xFFFDF8FF)
val SurfaceContainerLight = Color(0xFFF1EBFF)
val SurfaceContainerHighLight = Color(0xFFEBE5FF)
val SurfaceContainerHighestLight = Color(0xFFE5DEFF)
val SurfaceContainerLowLight = Color(0xFFF7F1FF)
val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
val SurfaceDimLight = Color(0xFFDDD5FF)

val PrimaryFixed = Color(0xFFDEDDFA)
val PrimaryFixedDim = Color(0xFFD0CFEB)
val OnPrimaryFixed = Color(0xFF3B3C52)
val OnPrimaryFixedVariant = Color(0xFF57586F)
val SecondaryFixed = Color(0xFFE8F7C3)
val SecondaryFixedDim = Color(0xFFDAE9B6)
val OnSecondaryFixed = Color(0xFF404C27)
val OnSecondaryFixedVariant = Color(0xFF5C6941)
val TertiaryFixed = Color(0xFFE2FC8B)
val TertiaryFixedDim = Color(0xFFD4ED7F)
val OnTertiaryFixed = Color(0xFF3E4E00)
val OnTertiaryFixedVariant = Color(0xFF586C06)

val splitItColorSchema = lightColorScheme(
    primary = PrimaryLight,
    onPrimary = OnPrimaryLight,
    primaryContainer = PrimaryContainerLight,
    onPrimaryContainer = OnPrimaryContainerLight,
    inversePrimary = InversePrimaryLight,
    secondary = SecondaryLight,
    onSecondary = OnSecondaryLight,
    secondaryContainer = SecondaryContainerLight,
    onSecondaryContainer = OnSecondaryContainerLight,
    tertiary = TertiaryLight,
    onTertiary = OnTertiaryLight,
    tertiaryContainer = TertiaryContainerLight,
    onTertiaryContainer = OnTertiaryContainerLight,
    background = BackgroundLight,
    onBackground = OnBackgroundLight,
    surface = SurfaceLight,
    onSurface = OnSurfaceLight,
    surfaceVariant = SurfaceVariantLight,
    onSurfaceVariant = OnSurfaceVariantLight,
    surfaceTint = SurfaceTintLight,
    inverseSurface = InverseSurfaceLight,
    inverseOnSurface = InverseOnSurfaceLight,
    error = ErrorLight,
    onError = OnErrorLight,
    errorContainer = ErrorContainerLight,
    onErrorContainer = OnErrorContainerLight,
    outline = OutlineLight,
    outlineVariant = OutlineVariantLight,
    scrim = ScrimLight,
    surfaceBright = SurfaceBrightLight,
    surfaceContainer = SurfaceContainerLight,
    surfaceContainerHigh = SurfaceContainerHighLight,
    surfaceContainerHighest = SurfaceContainerHighestLight,
    surfaceContainerLow = SurfaceContainerLowLight,
    surfaceContainerLowest = SurfaceContainerLowestLight,
    surfaceDim = SurfaceDimLight,
    primaryFixed = PrimaryFixed,
    primaryFixedDim = PrimaryFixedDim,
    onPrimaryFixed = OnPrimaryFixed,
    onPrimaryFixedVariant = OnPrimaryFixedVariant,
    secondaryFixed = SecondaryFixed,
    secondaryFixedDim = SecondaryFixedDim,
    onSecondaryFixed = OnSecondaryFixed,
    onSecondaryFixedVariant = OnSecondaryFixedVariant,
    tertiaryFixed = TertiaryFixed,
    tertiaryFixedDim = TertiaryFixedDim,
    onTertiaryFixed = OnTertiaryFixed,
    onTertiaryFixedVariant = OnTertiaryFixedVariant,
)